onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider multi_dac_spi_ldac_tb
add wave -noupdate /multi_dac_spi_ldac_tb/c_CLK_PERIOD
add wave -noupdate /multi_dac_spi_ldac_tb/c_CLK_PERIOD_HALF
add wave -noupdate /multi_dac_spi_ldac_tb/c_CLK_FREQ
add wave -noupdate /multi_dac_spi_ldac_tb/c_SCLK_PERIOD
add wave -noupdate /multi_dac_spi_ldac_tb/c_SCLK_PERIOD_HALF
add wave -noupdate /multi_dac_spi_ldac_tb/c_SCLK_FREQ
add wave -noupdate /multi_dac_spi_ldac_tb/c_CLK_SYNC_PERIOD
add wave -noupdate /multi_dac_spi_ldac_tb/c_CLK_SYNC_PERIOD_HALF
add wave -noupdate /multi_dac_spi_ldac_tb/c_CLK_SYNC_FREQ
add wave -noupdate /multi_dac_spi_ldac_tb/clk
add wave -noupdate /multi_dac_spi_ldac_tb/rst_n
add wave -noupdate /multi_dac_spi_ldac_tb/rst_sync_n
add wave -noupdate /multi_dac_spi_ldac_tb/clk_sync
add wave -noupdate /multi_dac_spi_ldac_tb/dac_data
add wave -noupdate /multi_dac_spi_ldac_tb/dac_start
add wave -noupdate /multi_dac_spi_ldac_tb/ready
add wave -noupdate /multi_dac_spi_ldac_tb/done_pp
add wave -noupdate /multi_dac_spi_ldac_tb/dac_cs_n
add wave -noupdate /multi_dac_spi_ldac_tb/dac_ldac_n
add wave -noupdate /multi_dac_spi_ldac_tb/dac_sck
add wave -noupdate -divider multi_dac_ldac
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/c_LDAC_WAIT_CYCLES
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/c_LDAC_WIDTH_CYCLES
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/g_CLK_FREQ
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/g_SCLK_FREQ
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/g_REF_CLK_LDAC_FREQ
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/g_NUM_DACS
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/g_USE_REF_CLK_LDAC
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/g_CPOL
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/g_LDAC_WIDTH
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/g_LDAC_WAIT_AFTER_CS
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/clk_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/rst_n_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/clk_ref_ldac_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/rst_ref_ldac_n_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/start_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/ready_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/done_pp_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/data_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/dac_cs_n_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/dac_ldac_n_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/dac_sck_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/dac_sdi_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/state_ready
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/state_ldac
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/clk_fsm
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/rst_fsm_n
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/done_trans_pp
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/done_trans_pp_ref_ldac
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/done_trans_pp_fsm
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/done_ldac_pp
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/done_ldac_pp_ref_sys
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/ready
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/ldac_n
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/ldac_wait_counter
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac/ldac_width_counter
add wave -noupdate -divider multi_dac_ldac_sync
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/c_LDAC_WAIT_CYCLES
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/c_LDAC_WIDTH_CYCLES
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/g_CLK_FREQ
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/g_SCLK_FREQ
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/g_REF_CLK_LDAC_FREQ
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/g_NUM_DACS
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/g_USE_REF_CLK_LDAC
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/g_CPOL
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/g_LDAC_WIDTH
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/g_LDAC_WAIT_AFTER_CS
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/clk_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/rst_n_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/clk_ref_ldac_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/rst_ref_ldac_n_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/start_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/ready_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/done_pp_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/data_i
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/dac_cs_n_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/dac_ldac_n_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/dac_sck_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/dac_sdi_o
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/state_ready
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/state_ldac
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/clk_fsm
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/rst_fsm_n
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/done_trans_pp
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/done_trans_pp_ref_ldac
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/done_trans_pp_fsm
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/done_ldac_pp
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/done_ldac_pp_ref_sys
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/ready
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/ldac_n
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/ldac_wait_counter
add wave -noupdate /multi_dac_spi_ldac_tb/cmp_multi_dac_sync/ldac_width_counter
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {978 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 132
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {727 ns} {1215 ns}
